core/urls.py
from django.urls import path

from .views import profile_view, EditProfileView

app_name = 'core'

urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('edit_profile/', EditProfileView.as_view(), name='edit_profile'),
    path('addresses/', profile_view, name='manage_address'),
]

lookeyecare/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('product/', include('product.urls', namespace='product')),
    path('account/', include('core.urls', namespace='core')),
    path('', include('website.urls', namespace='website')),
    path('products', include('shopping.urls', namespace='shopping')),
    # path('photologue/', include('photologue.urls', namespace='photologue')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

optical/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('product.urls', namespace='product')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path, include
from .views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ContactListView,
)

app_name = 'product'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('contacts/', ContactListView.as_view(), name='contacts_list'),
    # path('<category>/', ProductListView.as_view(), name='product_list_filtered'),
    path('create/', ProductCreateView.as_view(), name='product_create'),
    path('<slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('<slug>/<color_gallery>/', ProductDetailView.as_view(), name='product_detail_color'),
    path('<slug>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('<slug>/delete/', ProductDeleteView.as_view(), name='product_delete'),
]

shopping/urls.py
from django.urls import path

from .views import (
    add_to_cart, remove_from_cart, thankyou, add_quantity, minus_quantity,
    CartView, OrderListView, OrderDetailView, PaymentView, CheckoutView, AddCouponView,
    RequestExchangeView, RequestRefundView, request_received
)

# from .views import register_view, login_view, logout_view

app_name = 'shopping'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('thankyou/', thankyou, name='thankyou'),
    path('add_to_cart/<slug:product_slug>/', add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<slug:cart_item_slug>/', remove_from_cart, name='remove_from_cart'),
    path('add_quantity/<slug:cart_item_slug>/', add_quantity, name='add_quantity'),
    path('minus_quantity/<slug:cart_item_slug>/', minus_quantity, name='minus_quantity'),
    path('orders/', OrderListView.as_view(), name='order_list'),
    path('orders/<slug>/', OrderDetailView.as_view(), name='order_detail'),
    path('add_coupon/', AddCouponView.as_view(), name='add_coupon'),
    path('request_exchange/', RequestExchangeView.as_view(), name='request_exchange'),
    path('request_refund/', RequestRefundView.as_view(), name='request_refund'),
    path('request_received/', request_received, name='request_received'),
]

product/models.py
from django.db import models
from django.shortcuts import redirect, reverse
from django.conf import settings
from autoslug import AutoSlugField
from django.db.models.signals import post_save
# from taggit.managers import TaggableManager


class ProductQueryset(models.QuerySet):

    def instock(self):
        return self.filter(inventory__gt=0)

    def outofstock(self):
        return self.filter(inventory__lte=0)


class ProductManager(models.Manager):
    # add a property for admin use

    # def get_queryset(self):  # required
    #     return super().get_queryset()

    def get_queryset(self):  # required
        return ProductQueryset(self.model, using=self._db)

    def instock(self):
        return self.get_queryset().instock()

    def outofstock(self):
        return self.get_queryset().outofstock()


CATEGORY_CHOICES = (
    ('C', 'Contact'),
    ('S', 'Sun'),
    ('O', 'Other')
)

GENDER_CHOICES = (
    ('M', 'Men'),
    ('W', 'Women'),
    ('K', 'Kid'),
    ('U', 'Unisex'),
    ('O', 'Other')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'On Sale'),
    ('N', 'New')
)

SIZE_CHOICES = (
    ('SM', 'Small'),
    ('M', 'Medium'),
    ('L', 'Large'),
    ('NA', 'NA')
)

SHAPE_CHOICES = (
    ('RT', 'Rectangle'),
    ('RD', 'Round'),
    ('A', 'Aviator'),
    ('G', 'Geometric'),
    ('NA', 'NA')
)


def image_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'products/{0}/{1}'.format(instance.name, filename)


def color_sample_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'colors/{0}_sample_{1}'.format(instance.color_name, filename)


class Color(models.Model):
    color_name = models.CharField(max_length=22)
    sample = models.ImageField(upload_to=color_sample_directory_path, blank=True, null=True)

    def __str__(self):
        return self.color_name


class BaseCurve(models.Model):
    bc = models.DecimalField(decimal_places=1, max_digits=2)

    def __str__(self):
        return str(self.bc)


class Diameter(models.Model):
    dia = models.FloatField()

    def __str__(self):
        return str(self.dia)


class Power(models.Model):
    power = models.FloatField()

    def __str__(self):
        return str(self.power)


class Cylinder(models.Model):
    cyl = models.FloatField()

    def __str__(self):
        return str(self.cyl)


class Axis(models.Model):
    axis = models.IntegerField()

    def __str__(self):
        return str(self.axis)


class HighLow(models.Model):
    hl = models.CharField(max_length=50)

    def __str__(self):
        return self.hl


class DN(models.Model):
    dn = models.CharField(max_length=50)

    def __str__(self):
        return self.dn


class AddOnPower(models.Model):
    add = models.CharField(max_length=22)

    def __str__(self):
        return self.add


class ContactColor(models.Model):
    cc = models.CharField(max_length=50)

    def __str__(self):
        return self.cc


class Product(models.Model):
    name = models.CharField(max_length=100)
    category = models.CharField(default='O', choices=CATEGORY_CHOICES, max_length=1)
    gender = models.CharField(default='U', choices=GENDER_CHOICES, max_length=1, blank=True)
    short_description = models.CharField(max_length=120, default='', blank=True)
    description = models.TextField(default='', blank=True)
    size = models.CharField(default='NA', choices=SIZE_CHOICES, max_length=2, blank=True)
    shape = models.CharField(default='NA', choices=SHAPE_CHOICES, max_length=2, blank=True)
    price = models.FloatField(default=0, blank=True)
    inventory = models.IntegerField(default=0, blank=True)

    # # contact data fields
    # base_curve = models.ManyToManyField(BaseCurve, default=None, blank=True, null=True)
    # diameter = models.ManyToManyField(Diameter, blank=True, null=True)
    # power = models.ManyToManyField(Power, blank=True, null=True)
    # cylinder = models.ManyToManyField(Cylinder, blank=True, null=True)
    # axis = models.ManyToManyField(Axis, blank=True, null=True)
    # high_low = models.ManyToManyField(HighLow, blank=True, null=True)
    # dn = models.ManyToManyField(DN, blank=True, null=True)
    # add_on_power = models.ManyToManyField(AddOnPower, blank=True, null=True)
    # contact_color = models.ManyToManyField(ContactColor, blank=True, null=True)

    # image = models.ImageField(upload_to=image_directory_path, default=0, blank=True, null=True)

    slug = AutoSlugField(populate_from='name', unique=True, editable=False)
    label = models.CharField(default='P', choices=LABEL_CHOICES, max_length=1, blank=True)
    off_percentage = models.FloatField(default=0, blank=True)
    objects = ProductManager()

    def __str__(self):
        return self.name

    def is_limited(self):
        if self.price > 50:
            return True
        else:
            return False

    @property
    def final_price(self):
        if self.label == 'S':
            return self.price * (1 - self.off_percentage)
        else:
            return self.price

    def get_absolute_url(self):
        return reverse("product:product_detail", kwargs={
            'slug': self.slug
        })


#     @property
#     def get_carts_count(self):
#         return self.cart.all().count()
#


def get_color_gallery_slug(instance):
    return '{0}_{1}'.format(instance.product, instance.color)


class ColorsGallery(models.Model):
    color = models.ForeignKey(Color, on_delete=models.SET_NULL, blank=True, null=True)
    product = models.ForeignKey(Product, related_name='colors_gallery', on_delete=models.CASCADE)
    slug = AutoSlugField(populate_from=get_color_gallery_slug, unique=True, editable=False)

    def __str__(self):
        return self.product.name + '' + self.color.color_name


def gallery_images_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'products/{0}/{1}_{2}'.format(
        instance.color_gallery.product.name,
        instance.color_gallery.color.color_name, filename)


class Images(models.Model):
    color_gallery = models.ForeignKey(ColorsGallery, related_name='images', on_delete=models.CASCADE, default=None)
    image = models.ImageField(upload_to=gallery_images_directory_path, verbose_name='Image')


class Contact(Product):
    # name = models.CharField(max_length=100)
    # # category = models.CharField(default='C', choices=CATEGORY_CHOICES, max_length=1)
    # # gender = models.CharField(default='U', choices=GENDER_CHOICES, max_length=1, blank=True)
    # short_description = models.CharField(max_length=120, default='', blank=True)
    # description = models.TextField(default='', blank=True)
    # # size = models.CharField(default='NA', choices=SIZE_CHOICES, max_length=2, blank=True)
    # # shape = models.CharField(default='NA', choices=SHAPE_CHOICES, max_length=2, blank=True)
    # price = models.FloatField(default=0, blank=True)
    # inventory = models.IntegerField(default=0, blank=True)
    # slug = AutoSlugField(populate_from='name', unique=True, editable=False)
    # label = models.CharField(default='P', choices=LABEL_CHOICES, max_length=1, blank=True)
    # off_percentage = models.FloatField(default=0, blank=True)
    # objects = ProductManager()

    # contact data fields
    base_curve = models.ManyToManyField(BaseCurve, default=None, blank=True, null=True)
    diameter = models.ManyToManyField(Diameter, blank=True, null=True)
    power = models.ManyToManyField(Power, blank=True, null=True)
    cylinder = models.ManyToManyField(Cylinder, blank=True, null=True)
    axis = models.ManyToManyField(Axis, blank=True, null=True)
    high_low = models.ManyToManyField(HighLow, blank=True, null=True)
    dn = models.ManyToManyField(DN, blank=True, null=True)
    add_on_power = models.ManyToManyField(AddOnPower, blank=True, null=True)
    contact_color = models.ManyToManyField(ContactColor, blank=True, null=True)

    # image = models.ImageField(upload_to=image_directory_path, default=0, blank=True, null=True)

shopping/forms.py
from django import forms
from django.forms import TextInput, Select

from .models import Address
from localflavor.us.us_states import CONTIGUOUS_STATES, US_STATES


class CheckoutForm(forms.Form):
    shipping_first_name = forms.CharField(required=False)
    shipping_last_name = forms.CharField(required=False)
    shipping_street_address = forms.CharField(required=False)
    shipping_apartment_address = forms.CharField(required=False)
    shipping_city = forms.CharField(required=False)
    shipping_state = forms.ChoiceField(choices=CONTIGUOUS_STATES, required=False)
    shipping_state.widget.attrs.update({'class': 'custom-select d-block w-100'})
    shipping_zipcode = forms.CharField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)

    # same_billing_address = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    # use_default_shipping = forms.BooleanField(required=False)
    # set_default_billing = forms.BooleanField(required=False)
    # use_default_billing = forms.BooleanField(required=False)

    # class Meta:
    #     model = Address
    #     fields = [
    #         'first_name', 'last_name', 'street_address', 'apartment_address', 'city', 'state', 'zipcode', 'default'
    #     ]
    #     widgets = {
    #         'street_address': TextInput(attrs={'placeholder': '123 Main St'}),
    #         'apartment_address': TextInput(attrs={'placeholder': 'Apartment or suite'}),
    #         'city': TextInput(attrs={'placeholder': 'Pittsburgh'}),
    #     }


class PaymentForm(forms.Form):
    billing_first_name = forms.CharField(required=False)
    billing_last_name = forms.CharField(required=False)
    billing_street_address = forms.CharField(required=False)
    billing_apartment_address = forms.CharField(required=False)
    billing_city = forms.CharField(required=False)
    billing_state = forms.ChoiceField(choices=CONTIGUOUS_STATES, required=False)
    billing_state.widget.attrs.update({'class': 'custom-select d-block w-100'})
    billing_zipcode = forms.CharField(required=False)
    use_default_billing = forms.BooleanField(required=False)
    same_billing_address = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    set_default_billing = forms.BooleanField(required=False)


class CouponForm(forms.Form):
    code = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Promo Code',
                'aria-label': 'Recipient\'s username',
                'aria-describedby': 'basic-addon2'
            }
        )
    )


class ExchangeForm(forms.Form):
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 5
    }))
    email = forms.EmailField()


class RefundForm(forms.Form):
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 5
    }))
    email = forms.EmailField()

templates/shopping/cart.html
{% extends "base.html" %}

{% load humanize %}
{% load cart_template_tags %}

{% block head_title %}
  Shopping Cart
{% endblock head_title %}

{% block content %}
  <table class="table table-hover table-bordered text-center">
    <thead>
    <tr class="text-center">
      <th scope="col">NO.</th>
      <th scope="col">Product Name</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Total Item Price</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart.items.all %}
      <tr>
        <td>
          {{ forloop.counter }}
        </td>
        <td class="text-left">
          <a href="{% url 'product:product_detail' item.product.slug %}">{{ item.product.name }}</a>
          {% if item.product.label == 'S' %}
            <span class="badge badge-pill danger-color ml-5">{{ item.product.get_label_display }}</span>
          {% endif %}

        </td>
        <td>
          {% if item.product.label == 'S' %}
            <span class="mr-2"><del>$ {{ item.product.price|intcomma }}</del></span>
            <span>$ {{ item.product.final_price|intcomma|floatformat:-2 }}</span>
          {% else %}
            <span>$ {{ item.product.final_price|intcomma|floatformat:-2 }}</span>
          {% endif %}
        </td>
        <td>
          <a href="#">
            <a href="{% url 'shopping:minus_quantity' item.slug %}">
              <i class="fas fa-minus mr-2"></i>
            </a>
            {{ item.quantity }}
            <a href="{% url 'shopping:add_quantity' item.slug %}">
              <i class="fas fa-plus ml-2"></i>
            </a>
        </td>
        <td>
          {{ item.get_total_final_price|intcomma|floatformat:-2 }}
          {% if item.product.label == 'S' %}
            <span class="badge badge-pill primary-color ml-5">
              Saving $ {{ item.get_amount_saved|intcomma|floatformat:-2 }}
            </span>
          {% endif %}
          <span>
            <a class="text-danger"
               href="{% url 'shopping:remove_from_cart' item.slug %}">
            <i class="fas fa-trash float-lg-right" data-toggle="tooltip" data-placement="top"
               title="Delete this item"></i>
            </a>
          </span>
        </td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="5">
          There is nothing in your cart
        </td>
      </tr>
    {% endfor %}
    </tbody>
    <tfoot>
    {% if cart.get_total %}
      <tr>
        <td colspan="4">
          <strong class="pull-right">Order total: </strong>
        </td>
        <td colspan="1">
          <strong>$ {{ cart.get_total|intcomma|floatformat:-2 }}</strong>
          {% if request.user|cart_total_saving %}
            <span class="badge badge-pill primary-color ml-5">
              Saving $ {{ request.user|cart_total_saving|intcomma|floatformat:-2 }}
            </span>
          {% endif %}
        </td>
      </tr>
    {% endif %}
    <tr>
      <td colspan="5">
        <a href="{% url 'product:product_list' %}" class="btn btn-outline-primary btn-lg mb-2">
          {% if cart.get_total %}
            Continue Shopping
            <i class="fas fa-shopping-basket ml-2"></i>
          {% else %}
            Add items to your cart
          {% endif %}
        </a>
        {% if cart.get_total %}
          <a class="btn btn btn-outline-primary btn-lg mb-2" href="{% url 'shopping:checkout' %}">
            Checkout
            <i class="fas fa-credit-card ml-2"></i>
          </a>
        {% endif %}
      </td>
    </tr>
    </tfoot>
  </table>
{% endblock content %}

templates/shopping/checkout.html
{% extends "base.html" %}

{% load humanize %}
{% load static %}
{% load cart_template_tags %}
{% load crispy_forms_tags %}

{% block head_title %}
  Checkout
{% endblock head_title %}

{% block content %}
  <link href="{% static 'css/stripe_form.css' %}" rel="stylesheet"/>


  <!--Main layout-->
  <main>
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="h2 text-center">Checkout</h2>
      <div class="text-center mb-2">
        <a href="{% url 'product:product_list' %}" class="btn btn-outline-primary btn-lg mb-2">
          Continue Shopping
          <i class="fas fa-shopping-basket ml-2"></i>
        </a>
        <a href="{% url 'shopping:cart' %}" class="btn btn-outline-primary btn-lg mb-2">
          Return to Cart
          <i class="fas fa-shopping-cart ml-2"></i>
        </a>
      </div>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form method="POST" class="card-body">
              {% csrf_token %}
              <h4>Shipping Address</h4>

              {% if profile.default_shipping_address %}
                <div class="custom-control custom-checkbox mt-5">
                  <input type="checkbox" class="custom-control-input" name="use_default_shipping"
                         id="use_default_shipping">
                  <label class="custom-control-label" for="use_default_shipping">
                    Use the default shipping address:
                    {{ profile.default_shipping_address.first_name }},
                    {{ profile.default_shipping_address.street_address|truncatechars:10 }}
                  </label>
                </div>

                <!--default Shipping info-->
                <div class="default_shipping_info" style="display: none">
                  <div class="row">
                    <div class="col-md-6">
                      <!--firstName lastNmae-->
                      <div class="md-form mb-lg-3">
                        <h5>
                          {{ profile.default_shipping_address.first_name }}
                          {{ profile.default_shipping_address.last_name }}
                        </h5>
                      </div>
                    </div>
                  </div>
                  <!--street_address-->
                  <div class="mb-lg-3">
                    <h5>{{ profile.default_shipping_address.street_address }}</h5>
                  </div>
                  <!--apartment_address-->
                  {% if profile.default_shipping_address.apartment_address %}
                    <div class="mb-lg-3">
                      <h5>{{ profile.default_shipping_address.apartment_address }}</h5>
                    </div>
                  {% endif %}
                  <div class="mb-lg-3">
                    <h5>
                      {{ profile.default_shipping_address.city }},
                      {{ profile.default_shipping_address.state }}
                      {{ profile.default_shipping_address.zipcode }}
                    </h5>
                  </div>
                </div>
                <!--default Shipping info-->
              {% endif %}

              <!--hide Shipping form-->
              <div class="hideable_shipping_form">
                <!--Grid row-->
                <div class="row">

                  <!--Grid column-->
                  <div class="col-md-6">

                    <!--firstName-->
                    <div class="md-form mb-lg-3">
                      <input type='text' id='shipping_first_name' name='shipping_first_name' class='form-control'/>
                      <label for="shipping_first_name" class="">First name</label>
                    </div>

                  </div>
                  <!--Grid column-->

                  <!--Grid column-->
                  <div class="col-md-6">

                    <!--lastName-->
                    <div class="md-form mb-lg-3">
                      <input type='text' id='shipping_last_name' name='shipping_last_name' class='form-control'/>
                      <label for="shipping_last_name" class="">Last name</label>
                    </div>

                  </div>
                  <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--address-->
                <div class="md-form mb-lg-3">
                  <input type='text' placeholder='123 Main St' id='shipping_street_address'
                         name='shipping_street_address'
                         class='form-control'/>
                  <label for="shipping_street_address" class="">Address</label>
                </div>

                <!--address-2-->
                <div class="md-form mb-lg-3">
                  <input type='text' placeholder='Apartment or suite' id='shipping_apartment_address'
                         name='shipping_apartment_address' class='form-control'/>
                  <label for="shipping_apartment_address" class="">Address 2 (optional)</label>
                </div>

                <!--Grid row-->
                <div class="row">

                  <!--Grid column-->
                  <div class="col-lg-4 col-md-2">
                    <!--city-->
                    <div class="md-form mb-2">
                      <input type='text' placeholder='Pittsburgh' id='shipping_city' name='shipping_city'
                             class='form-control'/>
                      <label for="shipping_city" class="">City</label>
                    </div>
                  </div>
                  <!--Grid column-->

                  <!--Grid column-->
                  <div class="col-lg-4 col-md-12 mb-2">

                    <label for="shipping_state">State</label>
                    {{ form.shipping_state }}
                    {#                  <select class="custom-select d-block w-100" id="shipping_state" required>#}
                    {#                    <option value="">Choose...</option>#}
                    {#                    <option>California</option>#}
                    {#                  </select>#}
                    <div class="invalid-feedback">
                      Please provide a valid state.
                    </div>

                  </div>
                  <!--Grid column-->

                  <!--Grid column-->
                  <div class="col-lg-4 col-md-6">
                    <!--zip-->
                    <div class="md-form mb-2">
                      <input type='text' id='shipping_zipcode' name='shipping_zipcode' class='form-control'/>
                      <label for="shipping_zipcode" class="">Zip Code</label>
                      <div class="invalid-feedback">
                        Zip code required.
                      </div>
                    </div>
                  </div>
                  <!--Grid column-->

                </div>
                <!--Grid row-->

                <div class="custom-control custom-checkbox mt-2">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping"
                         id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">
                    Store this shipping address for next time
                  </label>
                </div>

              </div>
              <!--hide Shipping form-->

              <hr class="mb-4">
              <div class="text-center">
                <button class="btn btn-outline-primary btn-lg h-auto btn-block" type="submit">
                  Continue to payment
                  <i class="fas fa-credit-card ml-2"></i>
                </button>
              </div>

            </form>

          </div>
          <!--Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            {#            <span class="badge badge-secondary badge-pill">{{ cart.items.count }}</span>#}
            <a href="{% url 'shopping:cart' %}">
              <span class="badge badge-info badge-pill">{{ request.user|cart_item_count }}</span>
            </a>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-2">

            {% for item in cart.items.all %}
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">{{ item.product.name }}
                    {% if item.quantity > 1 %}
                      <span class="text-muted"> x {{ item.quantity }}</span>
                    {% endif %}
                  </h6>
                  <small class="text-muted">Frame color or contact info</small>
                </div>
                <span class="text-muted">$ {{ item.get_total_final_price|intcomma|floatformat:-2 }}</span>
              </li>
            {% empty %}
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <h6 class="my-0 text-center">There is nothing in your cart</h6>
              </li>
            {% endfor %}

            {% if cart.coupon %}
              <li class="list-group-item d-flex justify-content-between bg-light">
                <div class="text-success">
                  <h6 class="my-0">Promo code</h6>
                  <small>{{ cart.coupon.code }}</small>
                </div>
                <span class="text-success">- $ {{ cart.get_coupon_saved|intcomma|floatformat:-2 }}</span>
              </li>
            {% endif %}

            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$ {{ cart.get_total|intcomma|floatformat:-2 }}</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2" action="{% url 'shopping:add_coupon' %}" method="POST">
            {% csrf_token %}
            <div class="input-group">
              {#              <input type="text" class="form-control" placeholder="Promo Code" aria-label="Recipient's username"#}
              {#                     aria-describedby="basic-addon2">#}
              {{ couponform.code }}
              <div class="input-group-append">
                <button class="btn btn-blue-grey btn-md waves-effect m-0" type="submit">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->


{% endblock content %}

{% block extra_scripts %}
  <script>
    window.onload = function () {
      var hideable_shipping_form = $('.hideable_shipping_form');
      var default_shipping_info = $('.default_shipping_info');

      var use_default_shipping = document.querySelector("input[name=use_default_shipping]");

      if (use_default_shipping) {
        use_default_shipping.addEventListener('change', function () {
          if (this.checked) {
            hideable_shipping_form.hide();
            default_shipping_info.show();
          } else {
            hideable_shipping_form.show();
            default_shipping_info.hide();
          }
        });
      }
    }
  </script>
{% endblock extra_scripts %}

templates/shopping/orders_list.html
{% extends "base.html" %}

{% load humanize %}
{% load tz %}

{% block head_title %}
  Orders List
{% endblock head_title %}

{% block content %}
  <h1 class="text-center">Your Orders</h1>
  <table class="table table-hover table-bordered text-center">
    <thead>
    <tr class="text-center">
      <th>Reference Code</th>
      <th>Order Placed</th>
      <th>Total</th>
      <th>Shipping</th>
    </tr>
    </thead>
    <tbody>
    {% for order in orders %}
      <tr>
        <td><a href="{% url 'shopping:order_detail' order.slug %}">{{ order.ref_code }}</a></td>

        <td>{{ order.create_time|localtime }}</td>

        <td>$ {{ order.total_amount|intcomma|floatformat:-2 }}</td>
        {% if order.is_shipped %}
          <td>Tracking link here</td>
        {% else %}
          <td>Preparing Shipping</td>
        {% endif %}
      </tr>
    {% empty %}
      <tr>
        <td colspan="4">
          There is nothing in your order history
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock content %}

templates/shopping/request_received.html
{% extends "base.html" %}

{% block head_title %}
  Thank You!
{% endblock head_title %}

{% block content %}

  <div class="text-center mb-2">
    <h4>Thank you!</h4>
    <h4>Your request has been received</h4>
    <a href="{% url 'product:product_list' %}" class="btn btn-outline-primary btn-lg mb-2">
      Continue Shopping
      <i class="fas fa-shopping-basket ml-2"></i>
    </a>
  </div>


{% endblock content %}