core/urls.py
from django.urls import path

from .views import profile_view, EditProfileView

app_name = 'core'

urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('edit_profile/', EditProfileView.as_view(), name='edit_profile'),
    path('addresses/', profile_view, name='manage_address'),
]

lookeyecare/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('product/', include('product.urls', namespace='product')),
    path('account/', include('core.urls', namespace='core')),
    path('', include('website.urls', namespace='website')),
    path('products', include('shopping.urls', namespace='shopping')),
    # path('photologue/', include('photologue.urls', namespace='photologue')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

optical/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('product.urls', namespace='product')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path, include
from .views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ContactListView,
)

app_name = 'product'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('contacts/', ContactListView.as_view(), name='contacts_list'),
    # path('<category>/', ProductListView.as_view(), name='product_list_filtered'),
    path('create/', ProductCreateView.as_view(), name='product_create'),
    path('<slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('<slug>/<color_gallery>/', ProductDetailView.as_view(), name='product_detail_color'),
    path('<slug>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('<slug>/delete/', ProductDeleteView.as_view(), name='product_delete'),
]

shopping/urls.py
from django.urls import path

from .views import (
    add_to_cart, remove_from_cart, thankyou, add_quantity, minus_quantity,
    CartView, OrderListView, OrderDetailView, PaymentView, CheckoutView, AddCouponView,
    RequestExchangeView, RequestRefundView, request_received
)

# from .views import register_view, login_view, logout_view

app_name = 'shopping'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('thankyou/', thankyou, name='thankyou'),
    path('add_to_cart/<slug:product_slug>/', add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<slug:cart_item_slug>/', remove_from_cart, name='remove_from_cart'),
    path('add_quantity/<slug:cart_item_slug>/', add_quantity, name='add_quantity'),
    path('minus_quantity/<slug:cart_item_slug>/', minus_quantity, name='minus_quantity'),
    path('orders/', OrderListView.as_view(), name='order_list'),
    path('orders/<slug>/', OrderDetailView.as_view(), name='order_detail'),
    path('add_coupon/', AddCouponView.as_view(), name='add_coupon'),
    path('request_exchange/', RequestExchangeView.as_view(), name='request_exchange'),
    path('request_refund/', RequestRefundView.as_view(), name='request_refund'),
    path('request_received/', request_received, name='request_received'),
]

product/models.py
from django.db import models
from django.shortcuts import redirect, reverse
from django.conf import settings
from autoslug import AutoSlugField
from django.db.models.signals import post_save
# from taggit.managers import TaggableManager


class ProductQueryset(models.QuerySet):

    def instock(self):
        return self.filter(inventory__gt=0)

    def outofstock(self):
        return self.filter(inventory__lte=0)


class ProductManager(models.Manager):
    # add a property for admin use

    # def get_queryset(self):  # required
    #     return super().get_queryset()

    def get_queryset(self):  # required
        return ProductQueryset(self.model, using=self._db)

    def instock(self):
        return self.get_queryset().instock()

    def outofstock(self):
        return self.get_queryset().outofstock()


CATEGORY_CHOICES = (
    ('C', 'Contact'),
    ('S', 'Sun'),
    ('O', 'Other')
)

GENDER_CHOICES = (
    ('M', 'Men'),
    ('W', 'Women'),
    ('K', 'Kid'),
    ('U', 'Unisex'),
    ('O', 'Other')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'On Sale'),
    ('N', 'New')
)

SIZE_CHOICES = (
    ('SM', 'Small'),
    ('M', 'Medium'),
    ('L', 'Large'),
    ('NA', 'NA')
)

SHAPE_CHOICES = (
    ('RT', 'Rectangle'),
    ('RD', 'Round'),
    ('A', 'Aviator'),
    ('G', 'Geometric'),
    ('NA', 'NA')
)


def image_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'products/{0}/{1}'.format(instance.name, filename)


def color_sample_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'colors/{0}_sample_{1}'.format(instance.color_name, filename)


class Color(models.Model):
    color_name = models.CharField(max_length=22)
    sample = models.ImageField(upload_to=color_sample_directory_path, blank=True, null=True)

    def __str__(self):
        return self.color_name


class BaseCurve(models.Model):
    bc = models.DecimalField(decimal_places=1, max_digits=2)

    def __str__(self):
        return str(self.bc)


class Diameter(models.Model):
    dia = models.FloatField()

    def __str__(self):
        return str(self.dia)


class Power(models.Model):
    power = models.FloatField()

    def __str__(self):
        return str(self.power)


class Cylinder(models.Model):
    cyl = models.FloatField()

    def __str__(self):
        return str(self.cyl)


class Axis(models.Model):
    axis = models.IntegerField()

    def __str__(self):
        return str(self.axis)


class HighLow(models.Model):
    hl = models.CharField(max_length=50)

    def __str__(self):
        return self.hl


class DN(models.Model):
    dn = models.CharField(max_length=50)

    def __str__(self):
        return self.dn


class AddOnPower(models.Model):
    add = models.CharField(max_length=22)

    def __str__(self):
        return self.add


class ContactColor(models.Model):
    cc = models.CharField(max_length=50)

    def __str__(self):
        return self.cc


class Product(models.Model):
    name = models.CharField(max_length=100)
    category = models.CharField(default='O', choices=CATEGORY_CHOICES, max_length=1)
    gender = models.CharField(default='U', choices=GENDER_CHOICES, max_length=1, blank=True)
    short_description = models.CharField(max_length=120, default='', blank=True)
    description = models.TextField(default='', blank=True)
    size = models.CharField(default='NA', choices=SIZE_CHOICES, max_length=2, blank=True)
    shape = models.CharField(default='NA', choices=SHAPE_CHOICES, max_length=2, blank=True)
    price = models.FloatField(default=0, blank=True)
    inventory = models.IntegerField(default=0, blank=True)

    # # contact data fields
    # base_curve = models.ManyToManyField(BaseCurve, default=None, blank=True, null=True)
    # diameter = models.ManyToManyField(Diameter, blank=True, null=True)
    # power = models.ManyToManyField(Power, blank=True, null=True)
    # cylinder = models.ManyToManyField(Cylinder, blank=True, null=True)
    # axis = models.ManyToManyField(Axis, blank=True, null=True)
    # high_low = models.ManyToManyField(HighLow, blank=True, null=True)
    # dn = models.ManyToManyField(DN, blank=True, null=True)
    # add_on_power = models.ManyToManyField(AddOnPower, blank=True, null=True)
    # contact_color = models.ManyToManyField(ContactColor, blank=True, null=True)

    # image = models.ImageField(upload_to=image_directory_path, default=0, blank=True, null=True)

    slug = AutoSlugField(populate_from='name', unique=True, editable=False)
    label = models.CharField(default='P', choices=LABEL_CHOICES, max_length=1, blank=True)
    off_percentage = models.FloatField(default=0, blank=True)
    objects = ProductManager()

    def __str__(self):
        return self.name

    def is_limited(self):
        if self.price > 50:
            return True
        else:
            return False

    @property
    def final_price(self):
        if self.label == 'S':
            return self.price * (1 - self.off_percentage)
        else:
            return self.price

    def get_absolute_url(self):
        return reverse("product:product_detail", kwargs={
            'slug': self.slug
        })


#     @property
#     def get_carts_count(self):
#         return self.cart.all().count()
#


def get_color_gallery_slug(instance):
    return '{0}_{1}'.format(instance.product, instance.color)


class ColorsGallery(models.Model):
    color = models.ForeignKey(Color, on_delete=models.SET_NULL, blank=True, null=True)
    product = models.ForeignKey(Product, related_name='colors_gallery', on_delete=models.CASCADE)
    slug = AutoSlugField(populate_from=get_color_gallery_slug, unique=True, editable=False)

    def __str__(self):
        return self.product.name + '' + self.color.color_name


def gallery_images_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'products/{0}/{1}_{2}'.format(
        instance.color_gallery.product.name,
        instance.color_gallery.color.color_name, filename)


class Images(models.Model):
    color_gallery = models.ForeignKey(ColorsGallery, related_name='images', on_delete=models.CASCADE, default=None)
    image = models.ImageField(upload_to=gallery_images_directory_path, verbose_name='Image')


class Contact(Product):
    # name = models.CharField(max_length=100)
    # # category = models.CharField(default='C', choices=CATEGORY_CHOICES, max_length=1)
    # # gender = models.CharField(default='U', choices=GENDER_CHOICES, max_length=1, blank=True)
    # short_description = models.CharField(max_length=120, default='', blank=True)
    # description = models.TextField(default='', blank=True)
    # # size = models.CharField(default='NA', choices=SIZE_CHOICES, max_length=2, blank=True)
    # # shape = models.CharField(default='NA', choices=SHAPE_CHOICES, max_length=2, blank=True)
    # price = models.FloatField(default=0, blank=True)
    # inventory = models.IntegerField(default=0, blank=True)
    # slug = AutoSlugField(populate_from='name', unique=True, editable=False)
    # label = models.CharField(default='P', choices=LABEL_CHOICES, max_length=1, blank=True)
    # off_percentage = models.FloatField(default=0, blank=True)
    # objects = ProductManager()

    # contact data fields
    base_curve = models.ManyToManyField(BaseCurve, default=None, blank=True, null=True)
    diameter = models.ManyToManyField(Diameter, blank=True, null=True)
    power = models.ManyToManyField(Power, blank=True, null=True)
    cylinder = models.ManyToManyField(Cylinder, blank=True, null=True)
    axis = models.ManyToManyField(Axis, blank=True, null=True)
    high_low = models.ManyToManyField(HighLow, blank=True, null=True)
    dn = models.ManyToManyField(DN, blank=True, null=True)
    add_on_power = models.ManyToManyField(AddOnPower, blank=True, null=True)
    contact_color = models.ManyToManyField(ContactColor, blank=True, null=True)

    # image = models.ImageField(upload_to=image_directory_path, default=0, blank=True, null=True)

product/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate
from .models import Product, ColorsGallery, Images


# from django.conf import settings


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        # or defined the fields by specifically
        # fields = ['name', 'category', 'description', 'price', 'inventory']


class ColorsGalleryForm(forms.ModelForm):
    class Meta:
        model = ColorsGallery
        fields = ('color', 'product',)


class ImagesForm(forms.ModelForm):
    image = forms.ImageField(label='Image', required=False)

    class Meta:
        model = Images
        fields = ('color_gallery', 'image',)

# User = get_user_model()

# Register and Login Form are took care of by django-allauth

# class UserRegisterForm(forms.ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput)
#     confirm_password = forms.CharField(widget=forms.PasswordInput)
#
#     class Meta:
#         model = User
#         fields = [
#             'username', 'email', 'password', 'confirm_password'
#         ]
#
#     def clean(self, *args, **kwargs):
#         password = self.cleaned_data.get('password')
#         confirm_password = self.cleaned_data.get('confirm_password')
#         if password != confirm_password:
#             raise forms.ValidationError('The passwords do not match')
#         return super(UserRegisterForm, self).clean(*args, **kwargs)
#
#
# class UserLoginForm(forms.Form):
#     username = forms.CharField()
#     password = forms.CharField(widget=forms.PasswordInput)
#
#     def clean(self, *args, **kwargs):
#         username = self.cleaned_data.get('username')
#         password = self.cleaned_data.get('password')
#
#         if username and password:
#             user = authenticate(username=username, password=password)
#             if not user:
#                 raise forms.ValidationError('This user does not exist')
#             if not user.check_password(password):
#                 raise forms.ValidationError('The username or password was incorrect')
#             if not user.is_active:
#                 raise forms.ValidationError('This user is not active')
#         return super(UserLoginForm, self).clean(*args, **kwargs)

templates/product/contacts_list.html
{% extends "base.html" %}

{% load humanize %}

{% block head_title %}
  Products List
{% endblock head_title %}

{% block content %}

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg lighten-3 mt-3 mb-5 white scrolling-navbar">

        <!-- Navbar brand -->
        <span class="navbar-brand">Filter</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'product:contacts_list' %}">All</a>
            </li>

            <li class="nav-item">
              <form method="GET">
                <div class="form-inline">
                  <div class="form-group mr-2">
                    {% comment %}
                    <div class="form-check">
                      <input class="form-check-input ml-2" type="checkbox" id="women" name="women">
                      <label class="form-check-label" for="women">
                        Women
                      </label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input ml-2" type="checkbox" id="men" name="men">
                      <label class="form-check-label" for="men">
                        Men
                      </label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input ml-2" type="checkbox" id="kid" name="kid">
                      <label class="form-check-label" for="kid">
                        Kid
                      </label>
                    </div>
                    {% endcomment %}
                    <div class="form-check">
                      <input class="form-check-input ml-5" type="checkbox" id="onSale" name="onSale">
                      <label class="form-check-label" for="onSale">
                        On Sale
                      </label>
                    </div>
                    <button type="search" class="btn btn-outline- bg-transparent btn-sm">Apply</button>
                  </div>
                </div>
              </form>
            </li>
          </ul>
          <!-- Links -->

          <form method="GET">
            <div class="form-inline nav-item ">
              <div class="form-group">
                <div class="input-group">
                  <input class="form-control border-right-0 border" type="search" name="search_text"
                         placeholder="Search">
                  <span class="input-group-append">
                    <div class="input-group-text bg-transparent">
                        <button type="search"
                                class="fas fa-search icon-search icon-2x bg-transparent border-0"></button>
                    </div>
                  </span>
                </div>
              </div>
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

          {% for product in contacts %}

            <!--Grid column-->
            <div class="col-lg-4 col-xs-6 mb-4">

              <!--Card-->
              <div class="card">

                <!--Card image-->
                <div class="view overlay zoom">
                  <a href="{{ product.get_absolute_url }}" target='_blank'>
                    {#                    <img src="{{ product.image.url }}" class="card-img-top" alt="">#}
                    <img src="{{ product.colors_gallery.first.images.first.image.url }}" class="card-img-top" alt="">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>
                <!--Card image-->

                <!--Card content-->
                <div class="card-body text-center">
                  <!--Category & Title-->
                  <h5>
                    <strong>
                      <a href="{{ product.get_absolute_url }}" class="dark-grey-text" target='_blank'>{{ product.name }}
                        {% if product.label == 'N' %}
                          <span class="badge badge-pill secondary-color">{{ product.get_label_display }}</span>
                        {% elif product.label == 'S' %}
                          <span class="badge badge-pill danger-color">{{ product.get_label_display }}</span>
                        {% endif %}
                      </a>
                    </strong>
                  </h5>
                  <div>
                    {% for color_gallery in product.colors_gallery.all %}
                      <input type="image" class="color-display-tag" src="{{ color_gallery.color.sample.url }}" alt=""
                             style="width: 20px; height: 20px; background-size: cover; border-radius: 20px;"
                             data-toggle="tooltip" data-placement="top" title="{{ color_gallery.color.color_name }}">
                    {% endfor %}
                  </div>
                  {#                  <a href="" class="grey-text">#}
                  {#                    <h5>{{ product.get_category_display }}</h5>#}
                  {#                  </a>#}

                  <h4 class="font-weight-bold blue-text">
                    <strong>
                      {% if product.label == 'S' %}
                        <span class="mr-2"><del>$ {{ product.price|intcomma }}</del></span>
                        <span>$ {{ product.final_price|intcomma|floatformat:-2 }}</span>
                      {% else %}
                        <span>$ {{ product.final_price|intcomma|floatformat:-2 }}</span>
                      {% endif %}
                    </strong>
                  </h4>

                </div>
                <!--Card content-->

              </div>
              <!--Card-->

            </div>
          {% endfor %}
          <!--Grid column-->

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue text-lg-center">

            {% if page_obj.has_previous %}
              <!--Arrow left-->
              <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">
                  <span aria-hidden="true" style="font-size: large">1 &laquo;</span>
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                  <span aria-hidden="true" style="font-size: large">&lsaquo; Previous</span>
                </a>
              </li>
            {% endif %}

            <li class="page-item">
              <a class="page-link" href="#" style="font-size: large">{{ page_obj.number }}</a>
            </li>


            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                  <span aria-hidden="true" style="font-size: large">Next &rsaquo;</span>
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                  <span aria-hidden="true" style="font-size: large">&raquo; {{ page_obj.paginator.num_pages }}</span>
                </a>
              </li>
            {% endif %}

          </ul>
        </nav>
      {% endif %}
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->
  </div>

{% endblock content %}

{% block extra_body %}
  {% if request.user.is_superuser %}
    <div class="text-lg-center mt-5">
      <a class="btn btn-outline-primary mt=3" href="{% url 'product:product_create' %}">
        Create a Product
      </a>
    </div>
  {% endif %}
{% endblock extra_body %}

templates/product/product_confirm_delete.html
{% extends "base.html" %}

{% load humanize %}

{% block content %}

  <div class="col-16">
    <a class="btn btn-outline-primary" href="./..">Back to Product List</a>
    <div class="card mt-5">
      <div class="card-header">
        Product Name: {{ product.name }}
      </div>
      <div class="card-body">
        <p>Catogory: {{ product.category }}</p>
        <p>Description: {{ product.description }}</p>
        <p>Price: $ {{ product.price|intcomma }}</p>
        <img src="{{ product.image.url }}"/>
      </div>
      <div class="card-body">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-outline-primary" type="submit">Are you SURE?</button>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

templates/product/product_create.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block head_title %}
  Products Create
{% endblock head_title %}

{% block content %}

  <div class="col-16">
    <a class="btn btn-outline-primary" href="{% url 'product:product_list' %}">Back to Product List</a>
    <div class="card mt-5">
      <div class="card-header">
        <h4>Create a Product</h4>
      </div>
      <div class="card-body">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ product_form|crispy }}
          {{ color_gallery_form|crispy }}
          {{ image_forset.management_form }}
          {% for form in image_forset %}
            {{ form|crispy }}
          {% endfor %}
          <button class="btn btn-outline-primary" type="submit">Submit</button>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

templates/product/product_detail.html
{% extends "base.html" %}

{% load humanize %}

{% load i18n %}

{% block head_title %}{% trans product.name %}{% endblock %}

{% block content %}


  <!--Main layout-->
  <main class="mt-2">
    <div class="container dark-grey-text mt-2">
      <div class="row text-lg-center">
        {% if request.user.is_superuser %}
          <a href="./update" class="btn btn-outline-primary col-md-3">Update this product</a>
          <a href="./delete" class="btn btn-outline-primary col-md-3">delete this product</a>
          <h5 class="col-md-2 mt-3">In Stock: {{ product.inventory }}</h5>
        {% endif %}
      </div>

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Carousel Wrapper-->
          <div id="carousel-example-1z" class="carousel slide" data-ride="carousel" style="height: 400px">

            <!--Indicators-->
            <ol class="carousel-indicators">
              {% for image in color_gallery.images.all %}
                {% if forloop.counter == 1 %}
                  <li data-target="#carousel-example-1z" data-slide-to="{{ forloop.counter }}" class="active"></li>
                {% else %}
                  <li data-target="#carousel-example-1z" data-slide-to="{{ forloop.counter }}"></li>
                {% endif %}
              {% endfor %}
            </ol>
            <!--/.Indicators-->

            <!--Slides-->
            <div class="carousel-inner" role="listbox">

              {% for image in color_gallery.images.all %}

                <!--Single slide-->
                <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">

                  {#                  <div class="view"#}
                  {#                       style="background-image: url('{{ image.image.url }}'); background-repeat: no-repeat; background-size: cover;">#}

                  <div class="view">

                    <!-- Mask & flexbox options-->
                    <div class="mask d-flex justify-content-center align-items-center">

                      <!-- Content -->
                      <div class="text-center black-text mx-5 wow fadeIn">
                        <a href="{{ image.image.url }}" target="_blank">
                          <img src="{{ image.image.url }}" class="img-fluid mt-lg-5" alt="{{ product.name }}">
                        </a>
                      </div>
                      <!-- Content -->

                    </div>
                    <!-- Mask & flexbox options-->

                  </div>
                </div>
                <!--/single slide-->
              {% endfor %}

            </div>
            <!--/.Slides-->

            <!--Controls-->
            <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon rgba-black-light" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
              <span class="carousel-control-next-icon rgba-black-light" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
            <!--/.Controls-->

          </div>
          <!--/.Carousel Wrapper-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <strong>
                <h2 class="dark-grey-text">{{ product.name }}</h2>
                {% if product.label == 'N' %}
                  <span class="badge badge-pill secondary-color">{{ product.get_label_display }}</span>
                {% elif product.label == 'S' %}
                  <span class="badge badge-pill danger-color">{{ product.get_label_display }}</span>
                {% endif %}
              </strong>
            </div>
            <h4 class="font-weight-bold blue-text">
              <strong>
                {% if product.label == 'S' %}
                  <span class="mr-2"><del>$ {{ product.price|intcomma }}</del></span>
                  <span>$ {{ product.final_price|intcomma|floatformat:-2 }}</span>
                {% else %}
                  <span>$ {{ product.final_price|intcomma|floatformat:-2 }}</span>
                {% endif %}
              </strong>
            </h4>
            <div>
              {% for color_gallery in product.colors_gallery.all %}
                <a href="{% url 'product:product_detail_color' product.slug color_gallery.slug %}">
                  <img type="image" class="color-display-tag" src="{{ color_gallery.color.sample.url }}" alt=""
                       style="width: 20px; height: 20px; background-size: cover; border-radius: 20px;"
                       data-toggle="tooltip" data-placement="top" title="{{ color_gallery.color.color_name }}">
                </a>
              {% endfor %}
            </div>
            <p class="lead font-weight-bold">Description</p>
            <p>{{ product.description }}</p>
            <a href="{% url 'shopping:add_to_cart' product.slug %}" class="btn btn-outline-primary btn-lg mb-2">
              Add to cart
              <i class="fas fa-cart-arrow-down ml-1"></i>
            </a>
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Additional information. Additional information. Additional information.
            Additional information. Additional information. Additional information. </p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid"
               alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid"
               alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid"
               alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock %}