core/urls.py
from django.urls import path

from .views import profile_view, EditProfileView

app_name = 'core'

urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('edit_profile/', EditProfileView.as_view(), name='edit_profile'),
    path('addresses/', profile_view, name='manage_address'),
]

lookeyecare/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('product/', include('product.urls', namespace='product')),
    path('account/', include('core.urls', namespace='core')),
    path('', include('website.urls', namespace='website')),
    path('products', include('shopping.urls', namespace='shopping')),
    # path('photologue/', include('photologue.urls', namespace='photologue')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

optical/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('product.urls', namespace='product')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path, include
from .views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ContactListView,
)

app_name = 'product'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('contacts/', ContactListView.as_view(), name='contacts_list'),
    # path('<category>/', ProductListView.as_view(), name='product_list_filtered'),
    path('create/', ProductCreateView.as_view(), name='product_create'),
    path('<slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('<slug>/<color_gallery>/', ProductDetailView.as_view(), name='product_detail_color'),
    path('<slug>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('<slug>/delete/', ProductDeleteView.as_view(), name='product_delete'),
]

shopping/urls.py
from django.urls import path

from .views import (
    add_to_cart, remove_from_cart, thankyou, add_quantity, minus_quantity,
    CartView, OrderListView, OrderDetailView, PaymentView, CheckoutView, AddCouponView,
    RequestExchangeView, RequestRefundView, request_received
)

# from .views import register_view, login_view, logout_view

app_name = 'shopping'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('thankyou/', thankyou, name='thankyou'),
    path('add_to_cart/<slug:product_slug>/', add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<slug:cart_item_slug>/', remove_from_cart, name='remove_from_cart'),
    path('add_quantity/<slug:cart_item_slug>/', add_quantity, name='add_quantity'),
    path('minus_quantity/<slug:cart_item_slug>/', minus_quantity, name='minus_quantity'),
    path('orders/', OrderListView.as_view(), name='order_list'),
    path('orders/<slug>/', OrderDetailView.as_view(), name='order_detail'),
    path('add_coupon/', AddCouponView.as_view(), name='add_coupon'),
    path('request_exchange/', RequestExchangeView.as_view(), name='request_exchange'),
    path('request_refund/', RequestRefundView.as_view(), name='request_refund'),
    path('request_received/', request_received, name='request_received'),
]

website/urls.py
from django.urls import path

from .views import (
    HomeView, CollectionsView, LensTechView, OurServicesView, BookExamView, InsurancePromotionView, ContactsView,
    MeetUsView,
    TomFordView, GucciView, CartierView, LindbergView, RayBanView, OakleyView, BurberryView, BoucheronView,
    SaintLaurentView, FreakshowView, VinylFactoryView, BottegaVenetaView, HenryJullienView, McqView, SwarovskiView,
    StellaKidsView, ZegnaView, PlmView, LookEyeWareView
)

app_name = 'website'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('collections/', CollectionsView.as_view(), name='collections'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('lens_tech/', LensTechView.as_view(), name='lens_tech'),
    path('our_services/', OurServicesView.as_view(), name='our_services'),
    path('book_exam/', BookExamView.as_view(), name='book_exam'),
    path('insurance_promotion/', InsurancePromotionView.as_view(), name='insurance_promotion'),
    path('meet_us/', MeetUsView.as_view(), name='meet_us'),

    path('tom_ford/', TomFordView.as_view(), name='tom_ford'),
    path('gucci/', GucciView.as_view(), name='gucci'),
    path('cartier/', CartierView.as_view(), name='cartier'),
    path('lindberg/', LindbergView.as_view(), name='lindberg'),
    path('ray_ban/', RayBanView.as_view(), name='ray_ban'),
    path('oakley/', OakleyView.as_view(), name='oakley'),
    path('burberry/', BurberryView.as_view(), name='burberry'),
    path('boucheron/', BoucheronView.as_view(), name='boucheron'),
    path('saint_laurent/', SaintLaurentView.as_view(), name='saint_laurent'),
    path('freakshow/', FreakshowView.as_view(), name='freakshow'),
    path('vinyl_factory/', VinylFactoryView.as_view(), name='vinyl_factory'),
    path('bottega_veneta/', BottegaVenetaView.as_view(), name='bottega_veneta'),
    path('henry_jullien/', HenryJullienView.as_view(), name='henry_jullien'),
    path('mcq/', McqView.as_view(), name='mcq'),
    path('swarovski/', SwarovskiView.as_view(), name='swarovski'),
    path('stella_kids/', StellaKidsView.as_view(), name='stella_kids'),
    path('zegna/', ZegnaView.as_view(), name='zegna'),
    path('plm/', PlmView.as_view(), name='plm'),
    path('look_eyeware/', LookEyeWareView.as_view(), name='look_eyeware'),
]

optical/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.shortcuts import redirect, reverse
from django.conf import settings
from autoslug import AutoSlugField
from django.db.models.signals import post_save


class User(AbstractUser):
    pass

    def __str__(self):
        return self.username
        # return f"{self.first_name} {self.last_name}"


# GENDER_CHOICES = (
#     # max length = 1, use get_status_display() to return the display value
#     ('M', 'Male'),
#     ('F', 'Female'),
#     ('O', 'Other'),
#     ('N', 'Not Available')
# )


class ProductQueryset(models.QuerySet):

    def instock(self):
        return self.filter(inventory__gt=0)

    def outofstock(self):
        return self.filter(inventory__lte=0)


class ProductManager(models.Manager):
    # add a property for admin use

    # def get_queryset(self):  # required
    #     return super().get_queryset()

    def get_queryset(self):  # required
        return ProductQueryset(self.model, using=self._db)

    def instock(self):
        return self.get_queryset().instock()

    def outofstock(self):
        return self.get_queryset().outofstock()


class Product(models.Model):
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=50, default='Frame', blank=True)
    description = models.TextField(default='', blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, blank=True)
    inventory = models.IntegerField(default=0, blank=True)
    image = models.ImageField(blank=True, null=True)
    # slug = models.SlugField()
    slug = AutoSlugField(populate_from='name', always_update=True)

    objects = ProductManager()

    def __str__(self):
        return self.name

    def is_limited(self):
        if self.price > 50:
            return True
        else:
            return False

    def get_absolute_url(self):
        return reverse("optical:product_detail", kwargs={
            'slug': self.slug
        })

    @property
    def get_carts_count(self):
        return self.cart.all().count()


class Cart(models.Model):
    products = models.ManyToManyField(Product, related_name='cart')
    user = models.OneToOneField(User, related_name='carts', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def products_list(self):
        return self.products.all()

    class Meta:
        verbose_name = 'Cart'
        verbose_name_plural = 'Carts'


def post_user_signup_receiver(sender, instance, created, *args, **kwargs):
    # after User signup, a cart and shopping list will be created automatically
    if created:
        Cart.objects.get_or_create(user=instance)


# connect the signup with the actions by signal receiver
post_save.connect(post_user_signup_receiver, sender=User)

templates/home.html
{% extends "base.html" %}

{% load static %}


{% block extra_head %}
	<style type="text/css">
		html,
		body,
		header,
		.carousel {
			height: 60vh;
		}

		@media (max-width: 740px) {

			html,
			body,
			header,
			.carousel {
				height: 100vh;
			}
		}

		@media (min-width: 800px) and (max-width: 850px) {

			html,
			body,
			header,
			.carousel {
				height: 100vh;
			}
		}

	</style>
{% endblock extra_head %}


{% block home %}

	<!--Carousel Wrapper-->
	<div id="carousel-example-1z" class="carousel slide carousel-fade mt-5" data-ride="carousel">

		<!--Indicators-->
		<ol class="carousel-indicators">
			<li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
			<li data-target="#carousel-example-1z" data-slide-to="1"></li>
			<li data-target="#carousel-example-1z" data-slide-to="2"></li>
		</ol>
		<!--/.Indicators-->

		<!--Slides-->
		<div class="carousel-inner" role="listbox">

			<!--First slide-->
			<div class="carousel-item active">
				<div class="view"
				     style="background-image: url('{% static 'img/eyeware/boucheron.jpg' %}'); background-repeat: no-repeat; background-size: cover;">

					<!-- Mask & flexbox options-->
					<div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

						<!-- Content -->
						<div class="text-center white-text mx-5 wow fadeIn">
							<h1 class="mb-4">
								<strong>You're Always Welcome at Look Eye Care</strong>
							</h1>

							<h3>
								<strong>Quality Eye Care You Can Trust</strong>
							</h3>

							{#              <p class="mb-4 d-none d-md-block">#}
							{#                <strong>Some more words here</strong>#}
							{#              </p>#}

							<a class="btn btn-outline-white mt-5" href="{% url 'website:book_exam' %}"
							   target="_blank" role="button" style="font-size: 1rem">
								Book Your Exam Online
								<i class="far fa-calendar-alt ml-2"></i>
							</a>
						</div>
						<!-- Content -->

					</div>
					<!-- Mask & flexbox options-->

				</div>
			</div>
			<!--/First slide-->

			<!--Second slide-->
			<div class="carousel-item">
				<div class="view"
				     style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">

					<!-- Mask & flexbox options-->
					<div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

						<!-- Content -->
						<div class="text-center white-text mx-5 wow fadeIn">
							<h1 class="mb-4">
								<strong>BOGO SALE!!</strong>
							</h1>

							<p>
								<strong> 2nd PAIR OF LENSES FREE!!</strong>
							</p>

							<p class="mb-4 d-none d-md-block">
								<strong>In Store only</strong>
							</p>

							<a class="btn btn-outline-white mt-2" href="{% url 'website:book_exam' %}"
							   target="_blank" role="button" style="font-size: 1rem">
								Book Your Exam Online
								<i class="far fa-calendar-alt ml-2"></i>
							</a>
						</div>
						<!-- Content -->

					</div>
					<!-- Mask & flexbox options-->

				</div>
			</div>
			<!--/Second slide-->

			<!--Third slide-->
			<div class="carousel-item">
				<div class="view"
				     style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">

					<!-- Mask & flexbox options-->
					<div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

						<!-- Content -->
						<div class="text-center white-text mx-5 wow fadeIn">
							<h1 class="mb-4">
								<strong>Online Store Open</strong>
							</h1>

							<p>
								<strong>Place your order online</strong>
							</p>

							<p class="mb-4 d-none d-md-block">
								<strong>Stay in home and wait for your new glasses</strong>
							</p>

							<a target="_blank" href="{% url 'product:product_list' %}"
							   class="btn btn-outline-white btn-lg">
								Browse our online store
								<i class="fas fa-glasses ml-2"></i>
							</a>
						</div>
						<!-- Content -->

					</div>
					<!-- Mask & flexbox options-->

				</div>
			</div>
			<!--/Third slide-->

		</div>
		<!--/.Slides-->

		<!--Controls-->
		<a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
		<!--/.Controls-->

	</div>
	<!--/.Carousel Wrapper-->


	<!--Brand logo slides-->
	<div class="container">
		<div id="carouselExampleControls" class="carousel slide row mx-auto mt-0" data-ride="carousel"
		     style="height: 200px;">

			{#      <!--Indicators-->#}
			{#      <ol class="carousel-indicators">#}
			{#        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>#}
			{#        <li data-target="#carousel-example-1z" data-slide-to="1"></li>#}
			{#        <li data-target="#carousel-example-1z" data-slide-to="2"></li>#}
			{#        <li data-target="#carousel-example-1z" data-slide-to="3"></li>#}
			{#      </ol>#}
			{#      <!--/.Indicators-->#}

			<!--Controls-->
			<a class="carousel-control-prev mx-auto" href="#carouselExampleControls" role="button" data-slide="prev">
				<span class="carousel-control-prev-icon rgba-black-light" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>

			<!--Slides-->
			<div class="carousel-inner mx-auto">

				<!--First slide-->
				<div class="carousel-item active">

					<div class="view row align-content-center justify-content-center align-items-center">
						<div class="col-2">
							<a href="{% url 'website:tom_ford' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/tom_ford.png' %}" alt="1 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:gucci' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/gucci.jpg' %}" alt="2 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:cartier' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/cartier.png' %}" alt="3 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:lindberg' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/lindberg.jpg' %}" alt="4 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:ray_ban' %}" target="_blank">
								<img class="img-fluid"
								     src="{% static 'img/brand_logo/ray_ban.png' %}" alt="5 slide">
							</a>
						</div>
					</div>
				</div>
				<!--/First slide-->

				<!--Second slide-->
				<div class=" carousel-item">

					<div class="view row align-content-center justify-content-center align-items-center">
						<div class="col-2">
							<a href="{% url 'website:oakley' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/oakley.jpg' %}" alt="1 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:burberry' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/burberry.jpg' %}" alt="1 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:look_eyeware' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/look_eyeware.png' %}" alt="1 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:boucheron' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/boucheron.png' %}" alt="1 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:saint_laurent' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/saint_laurent.jpg' %}" alt="1 slide">
							</a>
						</div>
					</div>
				</div>
				<!--/Second slide-->

				<!--Third slide-->
				<div class="carousel-item">

					<div class="view row align-content-center justify-content-center align-items-center">
						<div class="col-2">
							<a href="{% url 'website:freakshow' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/freakshow.jpg' %}" alt="1 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:vinyl_factory' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/vinyl_factory.png' %}" alt="1 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:bottega_veneta' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/bottega_veneta.jpg' %}" alt="1 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:henry_jullien' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/henry_jullien.png' %}" alt="1 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:mcq' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/mcq.png' %}" alt="1 slide">
							</a>
						</div>
					</div>
				</div>
				<!--/Third slide-->

				<!--fourth slide-->
				<div class="carousel-item">

					<div class="view row align-content-center justify-content-center align-items-center">
						<div class="col-2">
							<a href="{% url 'website:swarovski' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/swarovski.jpg' %}" alt="1 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:stella_kids' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/stella_kids.jpg' %}" alt="1 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:zegna' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/zegna.png' %}" alt="1 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:plm' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/plm.jpg' %}" alt="1 slide">
							</a>
						</div>
						<div class="col-2">
							<a href="{% url 'website:look_eyeware' %}" target="_blank">
								<img class="img-fluid" src="{% static 'img/brand_logo/look_eyeware.png' %}" alt="1 slide">
							</a>
						</div>
					</div>
				</div>
				<!--/fourth slide-->

			</div>
			<!--/.Slides-->

			<a class="carousel-control-next mx-auto" href="#carouselExampleControls" role="button" data-slide="next">
				<span class="carousel-control-next-icon rgba-black-light" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>
			<!--/.Controls-->

		</div>
		<!--/.Brand logo slides-->
	</div>
	<!--/.Brand logo slides-->

	<div class="container">
		<div class="row text-center">
			<div class="col-sm-8">
				<div class="row card border border-dark text-left">
					<p class="ml-2 mr-2">Welcome to Look Eye Care, Pittsburgh’s premier eyewear boutique.  Conveniently
						located near
						you in Ross
						Park Mall, you’re just minutes away from 2020 designer and luxury brand glasses and sunglasses frames.</p>
					<p class="ml-2 mr-2">Dr. Yang and the Look Eye Care staff are committed to providing exceptional customer
						service experiences
						every step of the way including evening and weekend appointments with complementary fittings for life.</p>
					<p class="ml-2 mr-2">Look Eye Care provides the highest quality products and offers many same day
						services, from eye exams to
						prescription glasses in an hour utilizing the latest digital technologies.</p>
				</div>
				<div class="row mt-2">
					<div class="col-sm align-self-center">
						<a href="{% url 'website:our_services' %}"><h5><u>Our Services</u></h5></a>
						<p class="ml-2 text-left"><small>We strive to provide complete care for our patients.
							Learn
							more about
							all the services we provide and schedule your appointment today.</small></p>
					</div>
					<div class="col-sm">
						<img class="img-fluid rounded mr-2" src="{% static 'img/store_logo/Eye_Test_Glasses.webp' %}">
					</div>
				</div>

				<div class="row mt-2">
					<div class="col-sm align-self-center">
						<a href="{% url 'website:collections' %}"><h5><u>Our Eyewear</u></h5></a>
						<p class="ml-2 text-left"><small>Glasses say so much about your personality and personal style. At Look Eye
							Care, we are happy to work with you in selecting frames that complement your features. </small></p>
					</div>
					<div class="col-sm">
						<img class="img-fluid rounded mr-2" src="{% static 'img/store_logo/Lenses.webp' %}">
					</div>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="row">
					<script src="https://apps.elfsight.com/p/platform.js" defer></script>
					<div class="elfsight-app-404c7b0b-1598-4e06-bf9e-b878ca95fe83"></div>
				</div>
			</div>
		</div>
	</div>


{% endblock home %}

templates/messages.html
<div class="text-center mt-5">
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  {% endif %}
</div>

templates/navbar.html
{% load static %}
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <a class="nav-link" href="{% url 'website:home' %}">
      <img class="navbar-brand" src="{% static 'img/logo.jpg' %}" height="50px" width="50px">
    </a>

    <!-- Left -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'website:home' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
          Products
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'product:product_list' %}">Sun Glasses</a>
          <a class="dropdown-item" href="{% url 'product:contacts_list' %}" target="_blank">Contacts</a>
          <a class="dropdown-item" href="{% url 'website:collections' %}">Eyeware Collections</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'website:lens_tech' %}">Lens Technology</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'website:our_services' %}">Our Services</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'website:book_exam' %}" target="_blank">Book Exam</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'website:insurance_promotion' %}">Insurance & Promotion</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'website:meet_us' %}">Meet Us</a>
      </li>
    </ul>

    <!-- Right -->
    <ul class="navbar-nav mr-5">
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          {% if request.user.get_short_name != '' %}
            <a class="nav-link" style="color: black">Hello {{ request.user.get_short_name }}</a>
            {#              <a class="nav-link" style="color: black">Hello {{ request.user.first_name|title }}</a>#}
          {% else %}
            <a class="nav-link" style="color: black">Hello {{ request.user.username }}</a>
          {% endif %}
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shopping:cart' %}">
            <i class="fas fa-shopping-cart"></i>
            {{ request.user|cart_item_count }}
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
             aria-haspopup="true" aria-expanded="false">
            <i class="far fa-user"></i>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'core:profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'shopping:cart' %}">Shopping Cart</a>
            <a class="dropdown-item" href="{% url 'shopping:order_list' %}">Your Orders</a>
            <a class="dropdown-item" href="{% url 'shopping:request_exchange' %}">Request Exchange</a>
            <a class="dropdown-item" href="{% url 'shopping:request_refund' %}">Request Refund</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
          </div>
        </li>
      {% else %}

        {#        <li class="nav-item">#}
        {#          <a class="nav-link" style="color: black">Welcome !</a>#}
        {#        </li>#}

        <li class="nav-item">
          <a class="btn btn-outline-primary" href="{% url 'account_signup' %}">Signup</a>
        </li>
        <li class="nav-item">
          <a class="btn btn-outline-primary" href="{% url 'account_login' %}">Login</a>
        </li>
      {% endif %}
      {#        <li class="nav-item">#}
      {#          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>#}
      {#        </li>#}
    </ul>
    {#      for search bar only in product page#}
    {#      <form class="form-inline my-2 my-lg-0">#}
    {#        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
    {#        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
    {#      </form>#}
  </div>
</nav>
<hr/>